language: c++

install:
    - sudo apt-add-repository ppa:beineri/opt-qt594-trusty -y
    - sudo apt-get update
    - sudo apt-get install qt59base

script:
    source /opt/qt59/bin/qt59-env.sh && cd test && qmake && make -j && ./QtMockWebServerTest

branches:
    only:
        - master
